# fly.toml app configuration file generated for ws-bot on 2023-08-09T03:06:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ws-bot"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
